import "./globals.css";
import { Inter } from "next/font/google";
import { Chivo } from "next/font/google";
import { Nav } from "@/app/components/Nav";

const inter = Inter({ subsets: ["latin"] });
const chivo = Chivo({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={chivo.className + " debug-screens"}>
        <Nav />
        {children}
      </body>
    </html>
  );
}
